### ISSUE TITLE
Cannot create aws_acm_certificate_validation.cert

### ISSUE THREAD

**Issue by Colliwhopper** [linuxacademy/content-deploying-to-aws-ansible-terraform#2]
I've followed the course and all resources deploy fine except this one.
terraform apply just hangs trying to create it.
When creating the cert validation record resource, it cant see the name, record or type attributes, I get the error

"unresolved reference name" for each one. I've checked all the code is as per the course. Any idea?

resource "aws_route53_record" "cert_validation" {
  provider = aws.region-master
  for_each = {
    for val in aws_acm_certificate.jenkins-lb-https.domain_validation_val : val.domain_name => {
      name   = val.resource_record_name
      record = val.resource_record_value
      type   = val.resource_record_type
    }
  }
  name    = each.value.**name**
  records = [each.value.**record**]
  ttl     = 60
  type    = each.value.**type**
  zone_id = data.aws_route53_zone.dns.zone_id
}

**Comment by moosakhalidLA** [comment]
Hi @Colliwhopper ,

Can you attach Terraform debug logs here and the complete error here. For example , does it say which reference name is unresolved? 

Can you ensure that you are pasting in the correct domain name into the variables.tf? This step basically creates a certification validation record in the AWS Route53 domain that you own, which has to be a valid domain.

**Comment by moosakhalidLA** [comment]
Closing issue on no response. Please try the above recommended actions.
