### ISSUE TITLE
Error: Invalid reference from destroy provisioner

### ISSUE THREAD

**Issue by karimooo** [linuxacademy/content-deploying-to-aws-ansible-terraform#4]
Hi Khalid,

I can't resolve this issue on TF during final deployment : 

Error: Invalid reference from destroy provisioner
  on instances.tf line 74, in resource "aws_instance" "jenkins-worker-ireland":
  74:     inline = [
  75:       "java -jar /home/ec2-user/jenkins-cli.jar -auth @/home/ec2-user/jenkins_auth -s http://${aws_instance.jenkins-master.private_ip}:8080 delete-node ${self.private_ip}"
  76:     ]
Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.
References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.

any idea, i'm new on terraform.
Your course is very useful and dope, thanks a lot!

Karim

**Comment by moosakhalidLA** [comment]
Hi @karimooo ,
You are probably using a later version of Terraform than the one shown in the course.
Post version 0.13 in Terraform you can now reference attributes of a resource within its own provisioner using the self object, you are not allowed to reference external variable names even if they reference the same resource as it can cause cyclical dependencies, inside a provisioner i.e.
I have a modified version of this project which conforms to Terraform version 0.13, please refer to it for the solution. It should be in the directory `terraform_v13_compatible_code` in this same repository.

To pass the master private IP to the worker post 0.13 version, we basically assign a tag to the Jenkins worker with the value of the private IP by referencing the actual resource and then use the `self.Tags.<Tag-Key` to refer to it inside the provisioner, like so:

```
#Create EC2 in us-west-2
resource "aws_instance" "jenkins-worker-oregon" {
  provider                    = aws.region-worker
  count                       = var.workers-count
  ami                         = data.aws_ssm_parameter.linuxAmiOregon.value
  instance_type               = var.instance-type
  key_name                    = aws_key_pair.worker-key.key_name
  associate_public_ip_address = true
  vpc_security_group_ids      = [aws_security_group.jenkins-sg-oregon.id]
  subnet_id                   = aws_subnet.subnet_1_oregon.id
  provisioner "remote-exec" {
    when = destroy
    inline = [
      "java -jar /home/ec2-user/jenkins-cli.jar -auth @/home/ec2-user/jenkins_auth -s http://${self.tags.Master_Private_IP}:8080 -auth @/home/ec2-user/jenkins_auth delete-node ${self.private_ip} || echo 0"
    ]
    connection {
      type        = "ssh"
      user        = "ec2-user"
      private_key = file("~/.ssh/id_rsa")
      host        = self.public_ip
    }
  }

  provisioner "local-exec" {
    command = <<EOF
aws --profile ${var.profile} ec2 wait instance-status-ok --region ${var.region-worker} --instance-ids ${self.id} \
&& ansible-playbook --extra-vars 'passed_in_hosts=tag_Name_${self.tags.Name} master_ip=${self.tags.Master_Private_IP}' ansible_templates/install_worker.yaml
EOF
  }
  tags = {
    Name = join("_", ["jenkins_worker_tf", count.index + 1])
    Master_Private_IP = aws_instance.jenkins-master.private_ip ### <-------------
  }
  depends_on = [aws_main_route_table_association.set-worker-default-rt-assoc]
}
```
